version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - mosquitto_config:/mosquitto/config

volumes:
  mosquitto_data:
  mosquitto_log:
  mosquitto_config:

version: '3.5'

services:
	image: eclipse-mosquitto
	hostname: mosquitto
	container_name: mosquitto
	expose:
	    - "1883"
	    - "9001"
	ports:
	    - "1883:1883"
	    - "9001:9001"
	networks:
	    - default
	volumes:
	  - ./mosquitto-conf:/mosquitto/config
	restart: always

volumes:
	mosquitto-conf: ~
