version: '3.5'
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - default
    volumes:
      - ./mosquitto-conf:/mosquitto/config
    restart: always

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
  mosquitto-conf: ~
